### ISSUE TITLE
Playing a rive file in Google Chrome causes rendering failures when using transparency on .png images and transparent artboards

### ISSUE THREAD

**Issue by nmarafo** [rive-app/rive-flutter#250] opened 2022-08-11 12:39 UTC
-->

### Description
Playing a rive file in Google Chrome causes rendering failures when using transparency on .png images and transparent artboards. In Firefox for example It does not happen.

### Steps To Reproduce
1. Create a .riv file with .png transparency and transparent artboard
2. Play it in a flutter app with Chrome

#### Source `.riv`/`.rev` file
https://rive.app/community/3114-6568-test-render-in-chrome-with-png/

#### Screenshots

![test_render in chrome](https://user-images.githubusercontent.com/18734989/184135015-d2c250f5-4cab-435d-90cb-65c019c33da0.gif)

### Device & Versions 
```
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 20.04.4 LTS 5.15.0-43-generic, locale es_ES.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] VS Code (version 1.70.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```

**Comment by luigi-rosso** [comment] 2022-08-11 16:05
Likely root cause is this issue: https://github.com/flutter/flutter/issues/106433

You can mitigate it with either of these solutions:
https://github.com/flutter/flutter/issues/106433#issuecomment-1166149702
https://github.com/flutter/flutter/issues/106433#issuecomment-1188719478

We're using the first one in the Rive editor itself right now until the fix is in a stable Flutter build (which I believe it currently is not). 

So people don't have to go thread diving, this is the specific flag we're using:
```
BROWSER_IMAGE_DECODING_ENABLED=false
```

Full run command:
```
flutter -d chrome run --web-renderer=canvaskit --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false --release
```

**Comment by nmarafo** [comment] 2022-08-11 16:40
Thank you very much!! now it works perfectly.

**Comment by luigi-rosso** [comment] 2022-08-12 16:21
Np, I'll close for now!

**Closed by luigi-rosso** 2022-08-12 16:21 UTC
Labels: bug
