### ISSUE TITLE
Problem in loading multiple asset rives.

### ISSUE THREAD

**Issue by akanksha-coditas** [rive-app/rive-flutter#401] opened 2024-06-20 11:55 UTC
### Description
I'm encountering an issue with preloading Rive files using RiveFile.asset() in flutter web. For some files, the preloading works as expected, but for others, it throws exceptions. Interestingly, the files that cause exceptions when preloaded with others work fine when loaded individually. This problem occurs only when the files are loaded from hosted URLs.

### Steps To Reproduce
1. Add approx 10-12 rive files of less than 3mb size in assets directory. 
2. Now try to preload all the rives.
3. Few will be loaded and then will get an error saying

<img width="612" alt="Screenshot 2024-06-20 at 5 15 36 PM" src="https://github.com/rive-app/rive-flutter/assets/111876144/ec449cc1-2acb-4a6c-99bc-4a53e865aed8">

### Expected behavior
<-- A clear and concise description of what you expected to happen. -->
I wanted to preload all the rives at the initial state only and later on as per the requirement will render it on the screen using RiveFile.direct(riveFile).

### Device & Versions (please complete the following information)
- Device: Macbook Pro
- OS: macOs 14.4.1 Sonoma
- Flutter Version:  Flutter 3.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5dcb86f68f (6 weeks ago) • 2024-05-09 07:39:20 -0500
Engine • revision f6344b75dc
Tools • Dart 3.4.0 • DevTools 2.34.3

**Comment by HayesGordon** [comment] 2024-06-24 10:00
Hi @akanksha-coditas,

I'd like to confirm. Is this only an issue if the .riv file contains hosted out-of-band assets? It appears that the image data is corrupt.

If you have an example project (or .riv files) you can share with us that reproduces the issue that will be really helpful in speeding along our investigation.

**Comment by akanksha-coditas** [comment] 2024-06-24 10:56
> Hi @akanksha-coditas,
> 
> I'd like to confirm. Is this only an issue if the .riv file contains hosted out-of-band assets? It appears that the image data is corrupt.
> 
> If you have an example project (or .riv files) you can share with us that reproduces the issue that will be really helpful in speeding along our investigation.

Regarding the out-of-band asset, I am unsure. Additionally, I only see this problem when I load more than 6-7 rives at once; otherwise, everything functions as it should. Furthermore, it isn't targeting any particular file. Additionally, it makes no exceptions when I load files one at a time.

Also, I apologise, but since those are client files, I am unable to give them to you.

**Comment by HayesGordon** [comment] 2024-06-25 08:20
We can try to reproduce this issue on our end, but if you can provide a reproducible sample, or share how you are using the runtime code that'll be helpful. If we're unable to reproduce it'll be difficult to resolve the issue.

Could you give more information on this: "This problem occurs only when the files are loaded from hosted URLs."

**Comment by HayesGordon** [comment] 2024-08-29 12:24
Closing this issue as we're not able to reproduce this. But please reopen if you can provide a reproducible example

**Closed by HayesGordon** 2024-08-29 12:24 UTC
Labels: bug
