### ISSUE TITLE
Floating Action Button

### ISSUE THREAD

**Issue by Ben-Zoheth** [rive-app/rive-flutter#233] opened 2022-05-26 12:10 UTC
I want to make a floating action button. When the user tap on the button its shows the menu option when the user tap again on the floating action button menu buttons will be hidden.  Can you please tell me how I can make this button? 
![1](https://user-images.githubusercontent.com/104143251/170637343-c01dd384-551d-4af2-b073-661fd19e334e.jpg)

I just want animation like this. when the home screen is displayed it just shows the red button when the user tap on the red button then it shows the menu options green button. and when the user tap on the red button again it will close the menu options

**Comment by HayesGordon** [comment] 2023-02-01 12:53
Closing this as it's not a bug/issue. For support/help we recommend checking out our Discord channel: https://discord.com/invite/FGjmaTr

**Closed by HayesGordon** 2023-02-01 12:53 UTC
