### ISSUE TITLE
Null safety?

### ISSUE THREAD

**Issue by jacobaraujo7** [rive-app/rive-flutter#30] opened 2020-12-01 12:27 UTC
Are there plans for migration?

**Comment by luigi-rosso** [comment] 2020-12-03 03:33
Short answer: yes! 

Long answer: we're waiting for it to be out of beta. It'll involve a larger migration on our side as the bulk of the runtime code is actually auto-generated from our editor code. This guarantees high fidelity between what you see in the editor and what runs in the Flutter runtime (and less work for our small team), but it's a lot of code and it requires us to use portions of Flutter which aren't stable enough for our editor codebase.

**Comment by mjohnsullivan** [comment] 2020-12-07 20:45
Duplicate of #38

**Closed by mjohnsullivan** 2020-12-07 20:45 UTC
