### ISSUE TITLE
Shape "fill linear" opacity animation

### ISSUE THREAD

**Issue by mortifactor** [rive-app/rive-flutter#27] opened 2020-11-24 03:29 UTC
Hello.
I'm trying to hide object with opacity from 100 to 0. It's all fine, but if object has "fill" property with "linear" property it does not hide.
I'm running example in web with flutter beta channel and "rive: ^0.6.3".
Example riv file attached

[new_file_2.zip](https://github.com/rive-app/rive-flutter/files/5587258/new_file_2.zip)

**Comment by luigi-rosso** [comment] 2020-12-03 03:36
Thanks we'll take a look soon, definitely sounds like a bug. Do you see this in the editor too or only in your Flutter project?

**Comment by mortifactor** [comment] 2020-12-03 03:46
No, only in my Flutter project. The editor is good.

**Comment by luigi-rosso** [comment] 2021-02-14 18:28
Hi @mortifactor, could you please try ```rive: ^0.6.8``` to see if the issue is now resolved?

**Comment by mjohnsullivan** [comment] 2021-05-28 01:46
Closing this for now, but if you're still seeing the issue, please reopen.

**Closed** 2021-06-20 01:09 UTC
Labels: bug
