### ISSUE TITLE
The name 'Image' is defined in the libraries 'package:flutter/src/widgets/image.dart' and 'package:rive/src/rive_core/shapes/image.dart (via package:rive/rive.dart)'.

### ISSUE THREAD

**Issue by KyoShio** [rive-app/rive-flutter#421] opened 2024-09-13 18:51 UTC

**Comment by HayesGordon** [comment] 2024-09-16 08:59
Hey @KyoShio you can specify an [import prefix ](https://2dimensions.slack.com/archives/CLLCU09T6/p1723024783985659)to avoid this:

```dart
import 'package:rive/rive.dart' as rive;
```

Or optionally you can hide classes:

```dart
import 'package:rive/rive.dart' hide Image;
```

In the future we can maybe consider exposing an alias for the Image name, but there may always be clashes with Rive and the Flutter namespace. Closing this as it's not a bug.

**Closed by HayesGordon** 2024-09-16 08:59 UTC
Labels: bug

**Comment by Sarat-1997** [comment] 2024-09-23 08:07
@HayesGordon Thanks a lot bro!!

**Comment by SampleAssistRusira** [comment] 2025-01-24 05:11
This solution doesn't work for me.

I removed all the Image usages in the app but I still get this error when I run it

**Comment by gdaegeun539** [comment] 2025-02-10 02:24
Is there any plan to change rive's image class name?

I just upgrade my project flutter version 3.16.9 to 3.19.6 and rive 0.13.4 to 0.13.20, but all of my project files display collision of Image class...
